"""Project Euler Problem 29 - Distinct powers"""
if __name__ == "__main__":
	powers = []
	bound = range(2, 101)
	for a in bound:
		running_product = a
		for _ in bound:
			running_product *= a
			powers.append(running_product)
	print("The distinct terms in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100 is:", len(set(powers)))
